theme = "gruvbox"

[editor]
# Sync clipboard with system clipboard
default-yank-register = "+"
end-of-line-diagnostics = "hint"

[[language]]
name = "markdown"
comment-tokens = ["-", "+", "*", "- [ ]", ">"]
